google :
  client :
    clientId : 748145031843-gob7fh8imj88c4ngnuqt1b7e2c42q30b.apps.googleusercontent.com
    clientSecret: eset04h2YtTWcRWBCfW3SoZ4
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: email, profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
